version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: web_image
    ports:
      - "8080:8080"  # Exposes port 8080 of the container to 9000 on the host
    volumes:
      - .:/app  # Mounts the current directory to /app in the container
    env_file: 
      - .env  # Loads environment variables from the .env file
    depends_on:
      - dbb  # Ensures db starts before web

  dbb:
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "5434:5432"  # Exposes the PostgreSQL port
    environment:
      - POSTGRES_USER=${DATABASE_USER}  # Loads from the .env file
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persists PostgreSQL data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialize pgvector extension

volumes:
  postgres_data:
