version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg17  # Specify the correct tag here
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5436:5432"  # Host port 5436 mapped to container port 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"  # Django (Daphne) app
      - "8001:8001"  # Static files server

volumes:
  postgres_data:
