# Generated by Django 5.1.4 on 2024-12-25 19:13

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='answer',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='question',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='textchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(),
        ),
    ]
